package com.example.myapplication.models

enum class Language { RU, KK }

object Loc {
    private val ru = mapOf(
        "consoles" to "Консоли",
        "bar" to "Бар",
        "cart" to "Корзина",
        "stats" to "Касса",
        "free" to "Свободно",
        "busy" to "Занято",
        "booked" to "Бронь",
        "remaining" to "Осталось",
        "cost" to "Цена",
        "tap_to_start" to "Нажмите для начала",
        "select_session" to "Выберите сессию или пакет:",
        "packets" to "ПАКЕТЫ",
        "book" to "Забронировать",
        "client_name" to "Имя клиента",
        "confirm_booking" to "Подтвердить бронь",
        "clear_booking" to "Снять бронь",
        "close" to "Закрыть",
        "finish" to "Завершить",
        "add_to_cart" to "В корзину",
        "direct_sale" to "Прямая продажа",
        "add_to_console" to "Добавить к счету:",
        "cart_empty" to "Корзина пуста",
        "total" to "ИТОГО",
        "pay_kaspi" to "ОПЛАТИТЬ КАСПИ QR",
        "payment_qr" to "ОПЛАТА ПО QR",
        "scan_and_pay" to "Сканируйте и платите",
        "i_paid" to "Я ОПЛАТИЛ(А)",
        "total_revenue" to "ОБЩАЯ ВЫРУЧКА",
        "revenue_desc" to "Все доходы от закрытых сессий и продаж бара.",
        "enter_amount" to "Введите сумму в приложении Kaspi",
        "reserved_for" to "Забронировано на:",
        "session" to "Сессия",
        "started" to "Начало",
        "packet_price" to "Цена пакета",
        "until_stop" to "ДО УПОРА",
        "by_rate" to "По тарифу",
        "confirm" to "Подтвердить",
        "cancel" to "Отмена",
        "common" to "Общий",
        "vip" to "ВИП"
    )

    private val kk = mapOf(
        "consoles" to "Консольдар",
        "bar" to "Бар",
        "cart" to "Себет",
        "stats" to "Касса",
        "free" to "Бос",
        "busy" to "Бос емес",
        "booked" to "Брондалған",
        "remaining" to "Қалды",
        "cost" to "Құны",
        "tap_to_start" to "Бастау үшін басыңыз",
        "select_session" to "Сессияны немесе пакетті таңдаңыз:",
        "packets" to "ПАКЕТТЕР",
        "book" to "Брондау",
        "client_name" to "Клиент есімі",
        "confirm_booking" to "Брондауды растау",
        "clear_booking" to "Брондауды алып тастау",
        "close" to "Жабу",
        "finish" to "Аяқтау",
        "add_to_cart" to "Себетке",
        "direct_sale" to "Тікелей сату",
        "add_to_console" to "Шотқа қосу:",
        "cart_empty" to "Себет бос",
        "total" to "ЖИЫНЫ",
        "pay_kaspi" to "KASPI QR-МЕН ТӨЛЕУ",
        "payment_qr" to "QR-МЕН ТӨЛЕУ",
        "scan_and_pay" to "Сканерлеп, төлеңіз",
        "i_paid" to "МЕН ТӨЛЕДІМ",
        "total_revenue" to "ЖАЛПЫ ТҮСІМ",
        "revenue_desc" to "Жабылған сессиялар мен бар сатылымынан түскен барлық табыс.",
        "enter_amount" to "Kaspi қосымшасында соманы енгізіңіз",
        "reserved_for" to "Келесі адамға брондалған:",
        "session" to "Сессия",
        "started" to "Басталды",
        "packet_price" to "Пакет құны",
        "until_stop" to "ТОҚТАТҚАНША",
        "by_rate" to "Тариф бойынша",
        "confirm" to "Растау",
        "cancel" to "Бас тарту",
        "common" to "Жалпы",
        "vip" to "ВИП"
    )

    fun s(key: String, lang: Language): String {
        return if (lang == Language.RU) ru[key] ?: key else kk[key] ?: key
    }
}
